### ISSUE TITLE
Share count not updated

### ISSUE THREAD

**Issue by xroba** [djds4rce/angular-socialshare#22]
Hello and thanks for this Directive. I succed to install it via Git (I did not use bower). 

Nevertheless each time I want to share on Facebook All is properly working except that the counter of share is not incrementing ? I of course read the IMPORTANT note : 

"
For Correct Sharing of links and updating share count you must enable HTML5 Mode True for your application. i.e No # in URL'S .

angular.module('testing').config(function($locationProvider){
    $locationProvider.html5Mode(true).hashPrefix('!');
});
"

So if we try the plunkr demo 

this is the code I have now for script.js

```javascript
angular.module('testing',['djds4rce.angular-socialshare'])
.run(function($FB){
  $FB.init('386469651480295');
});

angular.module('testing').config(function($locationProvider){
   		 $locationProvider.html5Mode(true).hashPrefix('!');
	})

.controller('temp',function($scope){
  
});
```
Did I miss something ? 

Best Regards
Phoe

**Comment by djds4rce** [comment]
Are you testing it in localhost? If yes that could be a problem, Fb doesn't not consider locahost share as a valid share. If not please share the link with me Ill help you fix it.

**Comment by xroba** [comment]
Hello thanks for your prompt reply. No it's not on localhost :-). 

You may find a copy of your code adapted on this http://plnkr.co/edit/F0ZtBjAiT7B9LsFUCEgf?p=preview
I can share using Plunkr, but counter stays at 62 shares.  

Best Regards
Xavier

**Comment by djds4rce** [comment]
I will Give you a fix for this tommorrow. Its too late in the night for me
right now.

**Comment by djds4rce** [comment]
This is fixed please update to the latest version and it should work fine. Thanks for the bug report.

**Comment by xroba** [comment]
Hello, Thanks for your support really appreciate it. 

Nevertheless it still not working on my part :-/ I update the code (http://plnkr.co/edit/F0ZtBjAiT7B9LsFUCEgf?p=preview)

And,  the counter on Facebook or twitter is still not updated while the share (facebook / twitter) are on my Facebook/twitter Page. So it's really the counter that is not taking into account.

I m so sorry ... I should have missed something.
Best Regards
Phoe

**Comment by djds4rce** [comment]
Just find the Angular social share library code and find if the count is share_count or total_count. If its share_count you are using the old code. I tested this and it worked properly for me.

**Comment by djds4rce** [comment]
in your plunkr on line 8 use test.js instead of the remote minified library and its working for me. About twitter share count, There is no API from twitter for getting count and is auto updated by the widget so we are totally helpless on that and have to wait for twitter to update it automatically. Do reopen if it does not fix it for you.

**Comment by xroba** [comment]
Hello, thks again.

Sorry for Twitter it's working properly it just take a while before updated.  my mistake really sorry :-/.

But regarding the Facebook still not have counter updated. I can Share 10 times the same pages counter stays at same level.  ( i even try other pages that I never share before, and same things )

But I have a clue now :-).
So I looked at the facebook debug page : 
https://developers.facebook.com/tools/debug/og/object/
And add my url test : http://pxlbbq.com 
=> (there is 2 figures = Likes counter / share Counter)

Indeed the Share count is increasing But the figures that is show on the directive is not the share counter but it's the like counter. That's why it wasn't updated on the directive.

Now I have to figure how to get the total of both counter :-)

Best Regards

plunkr is currently using test.js : http://plnkr.co/edit/F0ZtBjAiT7B9LsFUCEgf?p=preview

**Comment by djds4rce** [comment]
I am fetching it from this URL https://api.facebook.com/method/links.getStats?urls=http://pxlbbq.com&format=json and showing count of both likes and shares currently.

**Comment by djds4rce** [comment]
If its isnt getting updated it is definitely some problem with the Facebook api which takes time to update the share count.

**Comment by xroba** [comment]
Hello, thanks for all,

Could be an issue based on the facebook api indeed

Even the link that's you are fetching : https://api.facebook.com/method/links.getStats?urls=http://pxlbbq.com&format=json

does not increment anything after sharing my pages via the plunkr (like nothing happend) :  http://plnkr.co/edit/F0ZtBjAiT7B9LsFUCEgf?p=preview

I will see on facebook support if there is a clue for this. 

If not I will find a way around :-).

Great thanks for your support !

**Comment by Bubimirac** [comment]
Dear djds4rce,

thanks for doing great job and sharing this library with us. I am also having troubles with displaying share count from FB - share count is always 0. Have you resolved this issue? How long does FB api takes to update?

Thanks and best regards!

**Comment by djds4rce** [comment]
Are you trying local host URL or a server URL? Afaik there is no problem
with the count getting updated.

**Comment by Bubimirac** [comment]
Hi,
thanks for the quick reply, I'm using public uri (on my test server). Can you maybe give me your private contact, so I can share the uri with you?
Thanks and greets.


		_____________________________

**Comment by djds4rce** [comment]
djd4rceatgmaildotcom I can only check it out after 12 hours as it is 12 am
for me right now
